FicProyecto_web/Areas/Carreras/Controllers/FicCarrerasController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FicProyecto_web.Areas.Carreras.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using static FicProyecto_web.Models.FicCarrera;

namespace FicProyecto_web.Areas.Carreras.Controllers
{
    [Area("Carreras")] //Se indica el area del controllador
    public class FicCarrerasController : Controller
    {

        // GET: FicCarreras
        public IActionResult Index()
        {
            try
            {
                FicSrvCatCarrerasLista FicServicio = new FicSrvCatCarrerasLista();
                cat_generales_consulta fic = new cat_generales_consulta();
                fic.eva_cat_carreras = FicServicio.FicGetListCatCarreras().Result;
                fic.cat_generales = FicServicio.FicGetListCatGenerales().Result;
                fic.cat_tipos_generales = FicServicio.FicGetListCatGeneralesTipo().Result;

                ViewBag.Title = "Catalogo de Carreras";
                return View(fic);
            }
            catch (Exception e)
            {
                throw;
            }
        }
        public IActionResult FicAdd()
        {
            try
            {
                FicSrvCatCarrerasLista FicServicio = new FicSrvCatCarrerasLista();
                cat_carreras_agregar temp = new cat_carreras_agregar();
                temp.cat_generales = FicServicio.FicGetListCatGenerales().Result;
                ViewBag.Title = "Agregar Carreras ";
                return View(temp);
            }
            catch (Exception e)
            {
                throw;
            }
        }
        public IActionResult FicDetail(Int16 idcarrera)
        {
            try
            {
                FicSrvCatCarrerasLista FicServicio = new FicSrvCatCarrerasLista();
                cat_carreras_agregar temp = new cat_carreras_agregar();
                temp.cat_generales = FicServicio.FicGetListCatGenerales().Result;
                temp.eva_cat_carreraslist = FicServicio.FicGetListCatCarreraID(idcarrera).Result;

                return View(temp);
            }
            catch (Exception e)
            {
                throw;
            }
        }
        public IActionResult FicEdit(Int16 idcarrera)
        {
            try
            {
                FicSrvCatCarrerasLista FicServicio = new FicSrvCatCarrerasLista();
                cat_carreras_agregar temp = new cat_carreras_agregar();
                temp.cat_generales = FicServicio.FicGetListCatGenerales().Result;
                temp.eva_cat_carreraslist = FicServicio.FicGetListCatCarreraID(idcarrera).Result;
                return View(temp);
            }
            catch (Exception e)
            {
                throw;
            }
        }
        public async Task<IActionResult> FicUpdateCarrera(cat_carreras_agregar m)
        {
            m.eva_cat_carreras.FechaUltMod = DateTime.Now;
            if (m.eva_cat_carreras.Activo == "on")
            {
                m.eva_cat_carreras.Activo = "S";
            }
            else
            {
                m.eva_cat_carreras.Activo = "N";
            }
            if (m.eva_cat_carreras.Borrado == "on")
            {
                m.eva_cat_carreras.Borrado = "S";
            }
            else
            {
                m.eva_cat_carreras.Borrado = "N";
            }
            FicSrvCatCarrerasLista FicServicio = new FicSrvCatCarrerasLista();
            bool FicLista = await FicServicio.FicUpdateCarrera(m.eva_cat_carreras);

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> FicAddCarrera(cat_carreras_agregar m)
        {

            m.eva_cat_carreras.FechaReg = DateTime.Now;
            m.eva_cat_carreras.FechaUltMod = DateTime.Now;//obtengo la fecha de mofificacion deszd el.sisgema
            if (m.eva_cat_carreras.Activo == "on")
            {
                m.eva_cat_carreras.Activo = "S";
            }
            else
            {
                m.eva_cat_carreras.Activo = "N";
            }
            if (m.eva_cat_carreras.Borrado == "on")
            {
                m.eva_cat_carreras.Borrado = "S";
            }
            else
            {
                m.eva_cat_carreras.Borrado = "N";
            }
            FicSrvCatCarrerasLista FicServicio = new FicSrvCatCarrerasLista();
            bool FicLista = await FicServicio.FicAddCarrera(m.eva_cat_carreras);

            TempData["Success"] = "Se agrego correctamente!";
            return RedirectToAction("Index");
        }
        public IActionResult FicDelete(Int16 idcarrera)
        {
            try
            {
                FicSrvCatCarrerasLista FicServicio = new FicSrvCatCarrerasLista();
                bool a = FicServicio.FicDeleteCatCarreraID(idcarrera).Result;
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                throw;
            }
        }

      
    }
}

FicProyecto_web/Areas/Generales/Controllers/FicGeneralesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FicProyecto_web.Areas.Carreras.Services;
using Microsoft.AspNetCore.Mvc;
using static FicProyecto_web.Models.FicCarrera;

namespace FicProyecto_web.Areas.Generales.Controllers
{
    [Area("Generales")]
    public class FicGeneralesController : Controller
    {
        /*------------------- GENERALES  CRUD------------------------------ */
        public IActionResult Index()
        {
          
            try
            {
                FicSrvCatGeneralesLista FicServicio = new FicSrvCatGeneralesLista();
                List<cat_generales> FicLista = FicServicio.FicGetListCatGenerales().Result;
                ViewBag.Title = "Catalogo de Generales";
                return View(FicLista);
            }
            catch (Exception e)
            {
                throw;
            }
        }
        

        public IActionResult FicGeneralAdd()
        {
            try
            {
                FicSrvCatGeneralesLista FicServicio = new FicSrvCatGeneralesLista();
                cat_generales_agregar temp = new cat_generales_agregar();
                temp.cat_tipos_generales = FicServicio.FicGetListCatGeneralesTipo().Result;
                return View(temp);
            }
            catch (Exception e)
            {
                throw;
            }
        }

        public IActionResult FicGeneralDetalle(Int16 idtipo)
        {
            try
            {
                FicSrvCatGeneralesLista FicServicio = new FicSrvCatGeneralesLista();
                cat_exportar_importar temp = new cat_exportar_importar();
                temp.cat_generales = FicServicio.FicGetListCatGeneralesID(idtipo).Result;
                temp.cat_tipos_generales = FicServicio.FicGetListCatGeneralesTipoID(temp.cat_generales[0].IdTipoGeneral).Result;
                return View(temp);
            }
            catch (Exception e)
            {
                throw;
            }
        }
        public async Task<IActionResult> FicAddGeneral(cat_generales_agregar m)
        {
            m.cat_generales.FechaReg = DateTime.Now;
            m.cat_generales.FechaUltMod = DateTime.Now;
            m.cat_generales.UsuarioReg = "FicIbarra";
            m.cat_generales.UsuarioMod = m.cat_generales.UsuarioReg;
            if (m.cat_generales.Activo == "on")
            {
                m.cat_generales.Activo = "S";
            }
            else
            {
                m.cat_generales.Activo = "N";
            }
            if (m.cat_generales.Borrado == "on")
            {
                m.cat_generales.Borrado = "S";
            }
            else
            {
                m.cat_generales.Borrado = "N";
            }
            FicSrvCatGeneralesLista FicServicio = new FicSrvCatGeneralesLista();
            bool FicLista = await FicServicio.FicAddGeneral(m.cat_generales);
            return RedirectToAction("Index");
        }
        public IActionResult FicDeleteGeneral(Int16 idgeneral)
        {
            try
            {
                 FicSrvCatGeneralesLista FicServicio = new FicSrvCatGeneralesLista();
                bool a = FicServicio.FicDeleteCatGeneralesID(idgeneral).Result;
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                throw;
            }
        }

        public  IActionResult FicGeneralUpdate(Int16 idGeneral)
        {
            try
            {
                FicSrvCatGeneralesLista FicServicio = new FicSrvCatGeneralesLista();
                cat_generales_editar temp = new cat_generales_editar();
                temp.cat_generales = FicServicio.FicGetListCatGeneralesID(idGeneral).Result;
                temp.cat_tipos_generales = FicServicio.FicGetListCatGeneralesTipo().Result;

                return View(temp);
            }
            catch (Exception e)
            {
                throw;
            }
        }
        public async Task<IActionResult> FicUpdateGeneral(cat_generales_agregar m)
        {
            m.cat_generales.UsuarioReg = "FicIbarra";
            m.cat_generales.UsuarioMod = m.cat_generales.UsuarioReg;
            m.cat_generales.FechaUltMod = DateTime.Now;
            if (m.cat_generales.Activo == "on")
            {
                m.cat_generales.Activo = "S";
            }
            else
            {
                m.cat_generales.Activo = "N";
            }
            if (m.cat_generales.Borrado == "on")
            {
                m.cat_generales.Borrado = "S";
            }
            else
            {
                m.cat_generales.Borrado = "N";
            }
            FicSrvCatGeneralesLista FicServicio = new FicSrvCatGeneralesLista();
            bool FicLista = await FicServicio.FicUpdateGenerales(m.cat_generales);

            return RedirectToAction("Index");
        }

        /*------------------- TIPO CRUD------------------------------ */
        public IActionResult ListaTipo()
        {

            try
            {
                FicSrvCatGeneralesLista FicServicio = new FicSrvCatGeneralesLista();
                List<cat_tipos_generales> FicLista = FicServicio.FicGetListCatGeneralesTipo().Result;
                ViewBag.Title = "Catalogo de Generales Tipo";
                return View(FicLista);
            }
            catch (Exception e)
            {
                throw;
            }
        }
        public IActionResult FicAddTipo()
        {
            try
            {
                ViewBag.Title = "Agregar Tipo";
                return View();
            }
            catch (Exception e)
            {
                throw;
            }
        }
        public async Task<IActionResult> FicTipoAdd(cat_tipos_generales m)
        {
            m.FechaReg = DateTime.Now;
            m.FechaUltMod = DateTime.Now;
            m.UsuarioReg = "FicIbarra";
            m.UsuarioMod = m.UsuarioReg;
            if (m.Activo == "on")
            {
                m.Activo = "S";
            }
            else
            {
                m.Activo = "N";
            }
            if (m.Borrado == "on")
            {
                m.Borrado = "S";
            }
            else
            {
                m.Borrado = "N";
            }
            FicSrvCatGeneralesLista FicServicio = new FicSrvCatGeneralesLista();
            bool FicLista = await FicServicio.FicAddTipo(m);

            return RedirectToAction("ListaTipo");
        }
        public IActionResult FicEditTipo(Int16 idtipo)
        {
            try
            {
                FicSrvCatGeneralesLista FicServicio = new FicSrvCatGeneralesLista();
                var temp = FicServicio.FicGetListCatGeneralesTipoID(idtipo).Result;
                return View(temp);
            }
            catch (Exception e)
            {
                throw;
            }
        }
        public async Task<IActionResult> FicUpdateTipo(cat_tipos_generales m)
        {
            m.UsuarioReg = "FicIbarra";
            m.UsuarioMod = m.UsuarioReg;
            m.FechaUltMod = DateTime.Now;
            if (m.Activo == "on")
            {
                m.Activo = "S";
            }
            else
            {
                m.Activo = "N";
            }
            if (m.Borrado == "on")
            {
                m.Borrado = "S";
            }
            else
            {
                m.Borrado = "N";
            }
            FicSrvCatGeneralesLista FicServicio = new FicSrvCatGeneralesLista();
            bool FicLista = await FicServicio.FicUpdateTipo(m);

            return RedirectToAction("ListaTipo");
        }
        public IActionResult FicDetialTipo(Int16 idtipo)
        {
            try
            {
                FicSrvCatGeneralesLista FicServicio = new FicSrvCatGeneralesLista();
                var temp = FicServicio.FicGetListCatGeneralesTipoID(idtipo).Result;
                return View(temp);
            }
            catch (Exception e)
            {
                throw;
            }
        }
        public IActionResult FicDeleteTipo(Int16 idtipo)
        {
            try
            {
                FicSrvCatGeneralesLista FicServicio = new FicSrvCatGeneralesLista();
                bool a = FicServicio.FicDeleteCatGeneralesTipoID(idtipo).Result;
                return RedirectToAction("ListaTipo");
            }
            catch (Exception e)
            {
                throw;
            }
        }
    }
}

FicProyecto_web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FicProyecto_web.Models;

namespace FicProyecto_web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FicProyecto_web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

FicProyecto_web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FicProyecto_web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Inicio Ana Carolina Mondragon Rangel";
}
<style>
    .cadrd-btn {
        transition: 0.7s;
    }
        .cadrd-btn:hover {
            background-color: #ffd8be;
        }
    .dashboard .pmd-card-body, .dashboard .notification .content-section {
        min-height: 50px;
    }
    .hvr-icon-grow {
        display: block;
    }
</style>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="pmd-card pmd-card-default pmd-z-depth ">
            <div class="pmd-card-title">
                <h2 class="pmd-card-title-text"><i class="fas fa-desktop"></i> Proyecto FIC</h2>
            </div>
            <div class="pmd-card-body">
                <center>
                    <img class="img-responsive" src="~/images/escudo_itt_200x200.png" />
                </center>
                <br />
                <div class="row">
                    <div class="col-md-12 col-lg-12">
                        <a asp-area="Carreras" class="hvr-icon-grow" asp-controller="FicCarreras" asp-action="Index">
                            <div class="pmd-card pmd-card-default pmd-z-depth-2 cadrd-btn ">
                                <div class="pmd-card-body">
                                    <center >
                                        <h1 class="pmd-card-title-text"><i class="fas fa-university fa-2x hvr-icon"></i> CARRERAS</h1>
                                    </center>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-6 col-lg-6">
                        <a asp-area="Especialidades" class="hvr-icon-grow" asp-controller="FicEspecialidades" asp-action="Index">
                            <div class="pmd-card pmd-card-default pmd-z-depth-2 cadrd-btn">
                                <div class="pmd-card-body">
                                    <center>
                                        <h1 class="pmd-card-title-text"><i class="fas fa-university fa-2x hvr-icon"></i> Especialidades</h1>
                                    </center>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-6 col-lg-6">

                        <a asp-area="Especialidades" class="hvr-icon-grow" asp-controller="FicEspecialidades" asp-action="IndexEC">
                            <div class="pmd-card pmd-card-default pmd-z-depth-2 cadrd-btn">
                                <div class="pmd-card-body">
                                    <center>
                                        <h1 class="pmd-card-title-text"><i class="fas fa-university fa-2x hvr-icon"></i> Especialidades Carrera</h1>
                                    </center>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-12 col-lg-12">
                        <a asp-area="Generales" class="hvr-icon-grow" asp-controller="FicGenerales" asp-action="Index">
                            <div class="pmd-card pmd-card-default pmd-z-depth-2 cadrd-btn">
                                <div class="pmd-card-body">
                                    <center>
                                        <h1 class="pmd-card-title-text"><i class="fas fa-university fa-2x hvr-icon"></i> GENERALES </h1>
                                    </center>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-12 col-lg-12">
                        <a asp-area="Generales" class="hvr-icon-grow" asp-controller="FicGenerales" asp-action="ListaTipo">
                            <div class="pmd-card pmd-card-default pmd-z-depth-2 cadrd-btn">
                                <div class="pmd-card-body">
                                    <center>
                                        <h1 class="pmd-card-title-text"><i class="fas fa-university fa-2x hvr-icon"></i> GENERALES TIPO</h1>
                                    </center>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>